# Default configuration for all microservices

security:  
  oauth2.resource:
    prefer-token-info: false
    user-info-uri: http://uaa/me
    load-balanced: true
    
logging:
  level:
    com.netflix.discovery: 'OFF'    
