# Default configuration for all microservices
security:
  ignored: /docs/**
  oauth2.resource:
    prefer-token-info: false
    user-info-uri: http://uaa/me
    load-balanced: true
    
logging:
  level:
    com.netflix.discovery: 'OFF'    
    
management:
  context-path: /manage    

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 3
    instance-info-replication-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 2
    eureka-connection-idle-timeout-seconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-In-seconds: 5
    
spring:
  application.index: ${spring.application.name}:${HOST:${random.value}}
